# -*- mode: ruby -*-
# vi: set ft=ruby :

CHEF_NODE_SCRIPT = <<EOF.freeze
apt-get update
apt-get -y install curl

# ensure the time is up to date
echo "Synchronizing time..."
apt-get -y install ntp
service ntp stop
sudo ntpd -s time.nist.gov
service ntp start
EOF

unless Vagrant.has_plugin?("vagrant-aws")
  raise 'vagrant-aws plugin is not installed!'
end

Vagrant.configure(2) do |config|
  # base box to use for aws
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.define 'chef-client' do |cc|
    cc.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['VAGRANT_AWS_ACCESS_KEY']
      aws.secret_access_key = ENV['VAGRANT_AWS_SECRET_KEY']
      aws.ami = ENV['VAGRANT_AWS_AMI_ID'] # ubuntu 16.04 for ap-southeast-1
      aws.region = ENV['VAGRANT_AWS_DEFAULT_REGION']
      aws.instance_type = "t2.micro"
      aws.keypair_name = ENV['VAGRANT_AWS_KEYPAIR_NAME']
      aws.security_groups = ['vagrant-vms-security-group']
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = ENV['VAGRANT_AWS_KEYPAIR_LOC']    
    end

    cc.vm.provision 'shell', inline: CHEF_NODE_SCRIPT.dup
    
    cc.vm.provision "chef_client" do |chef|
      chef.chef_server_url = "http://SERVER.INTERNAL.CNAME/organizations/agilityroots"
      chef.validation_key_path = "agilityroots-validator.pem"
      chef.validation_client_name = "agilityroots-validator"
    end 

  end
   
end
